public enum YokaiSE
{
    SE_UI_CLICK,
    SE_PURIFY_START,
    SE_PURIFY_SUCCESS,
    SE_PURIFY_CANCEL,
    SE_KEGARE_MAX_ENTER,
    SE_KEGARE_MAX_RELEASE,
    SE_EVOLUTION_START,
    SE_EVOLUTION_CHARGE,
    SE_EVOLUTION_FLASH,
    SE_EVOLUTION_SWAP,
    SE_EVOLUTION_COMPLETE
}
