public enum YokaiSE
{
    SE_UI_CLICK,
    SE_PURIFY_START,
    SE_PURIFY_SUCCESS,
    SE_PURIFY_CANCEL,
    SE_PURITY_EMPTY_ENTER,
    SE_PURITY_EMPTY_RELEASE,
    SE_SPIRIT_EMPTY,
    SE_SPIRIT_RECOVER,
    SE_EVOLUTION_START,
    SE_EVOLUTION_CHARGE,
    SE_EVOLUTION_FLASH,
    SE_EVOLUTION_SWAP,
    SE_EVOLUTION_COMPLETE
}
